server:
  port: 3000

pig:
  auth:
    clientId: ENC(LWeejg+IhLP2UX8reO/TSJg62+IAFj1u)
    clientSecret: ENC(LWeejg+IhLP2UX8reO/TSJg62+IAFj1u)
    scope: server
    
ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
feign:
  okhttp:
    enable: true
  httpclient:
    enable: false
    
spring:
  redis:
    host: 192.168.1.59
    port: 6379
    password: ENC(LWeejg+IhLP2UX8reO/TSJg62+IAFj1u)
#加密参数
jasypt:
  encryptor:
    password: lengleng
    
logging:
  config: classpath:logback.xml

