server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true

pig:
  auth:
    clientId: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    clientSecret: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    scope: server
    
logging:
  config: classpath:logback.xml

