server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true

pig:
  auth:
    clientId: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    clientSecret: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    scope: server
    
ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
feign:
  okhttp:
    enable: true
  httpclient:
    enable: false
    
spring:
  redis:
    host: 192.168.1.59
    port: 6379
    password: ENC(LWeejg+IhLP2UX8reO/TSJg62+IAFj1u)
#加密参数
jasypt:
  encryptor:
    password: lengleng
    
logging:
  config: classpath:logback.xml

